name: webify
description: Webify Framework Alternative Flutter Web Untuk Membangun app web dengan style code flutter.
version: 0.0.0
# homepage: https://www.example.com
homepage: https://youtube.com/@azkadev
repository: https://github.com/azkadev/webify.git
environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  alfred: ^1.0.0+1
  galaxeus_lib: ^0.0.34
